version: '3'
services:
  auth-service:
    build: .
    container_name: "sopa-auth"
    ports:
      - "8080:8080"
    volumes:
      - ./common_files/:/common_files
      - ./model/:/model
      - ./interfaces/:/interfaces
      - ./service/:/service
      - ./controller/:/controller
      - ./schema/:/schema
