# APPLICATION GLOBAL CONSTANTS
STAGE = "prod"
# DATABASE CLUSTER CREDENTIALS
MONGO_URI = "INSERT_YOUR_OWN"
DATABASE_NAME = "SOPA_CUSTOMER_APP"
USER_DB = "users"
OTP_DB = "otps"
USER_DETAILS_DB = "user_details"
TOKEN_DB = "expiring_tokens"
# COMMON CONSTANTS OF THE SERVICE

# SECRETS
TWILIO_NUMBER = "YOUR_TWILIO_NUMBER"
TWILIO_ACCOUNT_SID = 'YOUR_TWILIO_ACCOUNT_SID'
TWILIO_AUTH_TOKEN = 'YOUR_TWILIO_AUTH_TOKEN'
X_INTERNAL_KEY = 'YOUR_X_INTERNAL_KEY'
X_PRODUCT_KEY = 'auth'
